        <nav>
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="product.php">Product</a></li>
                <li><a href="enquire.php">Enquire</a></li>
                <li><a href="about.php">About</a></li>
                <li><a href="enhancements.php">Enhancements</a></li>
                <li><a href="log_in.php">Manager</a></li>
            </ul>
        </nav>